# Generated by Django 4.1.3 on 2022-11-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_delete_test03'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test02',
        ),
    ]
